feat(config): add config instead of secrets
fivethree-team/nestjs-prisma-starter pull request #420
Opened 2020-10-02 14:15 UTC by Oupsla

Hello 👋 

The goal of this PR is to use config files instead of storing everything in .env files (this allows to made complex structure instead of "just" strings in .env files, and to use .env files for secrets only).

For info, I have gone a bit further in my own work (but didn't have pushed this in this PR), by requiring a config file based on the NODE_ENV variable. This allows to have one config file for each environnement (and each environnement config file has to declare all variables, that can't be the case with .env files). Tell me if something like is interresting and I can open another PR 😄 

Have a nice weekend !

2020-10-02 14:20 UTC, marcjulian commented
@Oupsla thanks for your contribution this looks way cleaner than using the `.env` variables everywhere! I will review your PR asap!! Makes also more sense to *just* use `.env` for secrets rather than all configurations!

2020-10-02 14:47 UTC, marcjulian commented
@Oupsla wish you a great weekend too!

2020-10-03 10:32 UTC, marcjulian requested changes
LGTM 👍  thanks for simplifying configs!

I requested only small changes.

2020-10-03 10:32 UTC, marcjulian commented on src/configs/config.interface.ts
> +  bcryptSaltOrRound: number;
```suggestion
  bcryptSaltOrRound: string | number;
```

2020-10-03 10:32 UTC, marcjulian commented on src/configs/config.interface.ts
> +}
```suggestion
  schemaDestination: string;
  sortSchema: boolean;
}
```

2020-10-03 10:32 UTC, marcjulian commented on src/configs/config.ts
> +  },
```suggestion
    schemaDestination: './src/schema.graphql',
    sortSchema: true,
  },
```

2020-10-03 10:32 UTC, marcjulian commented on src/app.module.ts
> +          sortSchema: true,
```suggestion
          sortSchema: graphqlConfig.sortSchema,
```

2020-10-03 10:32 UTC, marcjulian commented on src/configs/config.interface.ts
> +  bcryptSaltOrRound: number;
Should be possible to provide a salt as `string`

2020-10-05 07:14 UTC, merged

2020-10-05 07:16 UTC, marcjulian commented
@Oupsla thanks again for your PR 👍 do you like to create another PR one for requiring a configuration file for each environment?

2020-10-05 07:19 UTC, Oupsla commented
@marcjulian, while working on a project (started with this template), I have noticed that Prisma has also a .env file, I have figured out a solution to use .env files at the root folder (using dotenv-cli). I'll make another PR with that, if you think that could be interesting.



> @Oupsla thanks again for your PR 👍 do you like to create another PR one for requiring a configuration file for each environment?

No problem, glad to help ! 😄  Yes I'll create a PR for that

2020-10-05 07:23 UTC, marcjulian commented
Awesome thank you, that will definitely be helpful for others as well.

2020-10-05 08:29 UTC, Oupsla commented
(Also if you don't mind adding `hacktoberfest` in topics of this repo, so my PR's could count, cause it is hard to fill the counter after this update : https://hacktoberfest.digitalocean.com/hacktoberfest-update 😄 
Sorry for the noise ! )