createUser errors don't capture all possible cases
fivethree-team/nestjs-prisma-starter pull request #426
Opened 2020-10-15 21:12 UTC by theRocket

anything that invalidates on prisma.create.user() will throw a duplicate email exception, which is confusing

2020-10-20 11:23 UTC, marcjulian commented
@theRocket thanks for the PR. You are correct to throw different error messages if `prisma.user.create()` fails.

We could do so by verifying if the error is an [PrismaClientKnownRequestError](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/error-reference#prismaclientknownrequesterror).

2020-10-20 11:27 UTC, marcjulian requested changes

2020-10-20 11:27 UTC, marcjulian commented on src/services/auth.service.ts
> +        //throw new ConflictException(`Email ${payload.email} already used.`); //not always the case
```suggestion
        if(e instanceof PrismaClientKnownRequestError && e.code === 'P2002') {
           throw new ConflictException(`Email ${payload.email} already used.`);
        } else {
           throw new Error(error);
        }
```

2020-10-20 11:27 UTC, marcjulian commented on src/services/auth.service.ts
> +        //throw new ConflictException(`Email ${payload.email} already used.`); //not always the case
What about throwing a Nestjs Exception like `InternalServerErrorException` in the else case?

2020-10-21 19:31 UTC, theRocket commented
I will take your changes and test.

2020-10-22 07:52 UTC, merged